### PR TITLE
Change to safeChecked Enforester::isDelimiter

### LINKED ISSUE #572: Enforester::createError assumes everything is a term
On the gitter channel we were trying to debug a problem (turned out to be object literals vs. labeled statements in blocks). Here's a link to the error:

https://gitter.im/sweet-js/sweet.js?at=57b12ac1a00c6adb45e6dff3

I'm guessing a `safeCheck` should fix it, but I don't have time to try it right now. I may submit a PR later this week.

### PR DESCRIPTION
**Pull request by gabejohnson**
fixes #572

### CODE REVIEW

File: src/enforester.js [hunk 1]
```diff
@@ -2255,7 +2255,7 @@ export class Enforester {
     let offending = stx;
     if (this.rest.size > 0) {
       ctx = this.rest.slice(0, 20).map(term => {
-        if (term.isDelimiter()) {
+        if (this.isDelimiter()) {
```
Comment (disnet) [inline src/enforester.js]: `this.isDelimiter(term)` is what you actually want

**Comment by gabejohnson** [comment]
@disnet fixed
